# Generated by Django 5.2.6 on 2025-10-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.TextField(default='unknown@example.com', verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.TextField(default='unknown@example.com', verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='sphere',
            field=models.TextField(default='unknown@example.com', verbose_name='Сфера'),
            preserve_default=False,
        ),
    ]
