# Generated by Django 5.2.6 on 2025-10-04 07:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_email_client_name_client_sphere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sphere',
            field=models.CharField(max_length=100, verbose_name='Сфера деятельности'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('deadline', models.DateField(verbose_name='Срок сдачи')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('on_hold', 'Приостановлен')], default='planning', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
