# Generated by Django 5.2.6 on 2025-10-06 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_work_date',
            field=models.DateField(verbose_name='Дата приёма на работу'),
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Выполняется'), ('approval', 'Согласуется'), ('review', 'На проверке'), ('revision', 'Доработка'), ('completed', 'Выполнена')], default='in_progress', max_length=20, verbose_name='Статус выполнения')),
                ('start_date', models.DateField(verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Планируемая дата завершения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_services', to='clients.employee', verbose_name='Ответственный сотрудник')),
                ('favour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_services', to='clients.favour', verbose_name='Услуга')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_services', to='clients.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Услуга в проекте',
                'verbose_name_plural': 'Услуги в проектах',
            },
        ),
    ]
