# Generated by Django 5.2.6 on 2025-10-06 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_employee_start_work_date_projectservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectservice',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.employee'),
        ),
        migrations.AlterField(
            model_name='projectservice',
            name='favour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.favour'),
        ),
        migrations.AlterField(
            model_name='projectservice',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.project'),
        ),
    ]
