# Generated by Django 5.2.6 on 2025-10-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_projectservice_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], default=5, verbose_name='Оценка')),
                ('feedback', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(verbose_name='Дата отзыва')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.project')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
