# Generated by Django 5.2.6 on 2025-10-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(verbose_name='Дата отзыва'),
        ),
    ]
