# Generated by Django 5.2.6 on 2025-11-02 18:49

from django.db import migrations

def fix_client_employee_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Client = apps.get_model('clients', 'Client')
    Employee = apps.get_model('clients', 'Employee')
    UserProfile = apps.get_model('general', 'UserProfile')
    
    # 1. Сначала убедимся, что у всех пользователей есть UserProfile
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)
    
    # 2. Исправим Client, у которых нет user или user=None
    for client in Client.objects.filter(user__isnull=True):
        # Создаем нового пользователя для этого клиента
        user = User.objects.create_user(
            username=f"client_fix_{client.id}",
            email=f"client_fix_{client.id}@example.com",
            password="temp_password_123"
        )
        client.user = user
        client.save()
        print(f"Создан пользователь для клиента {client.id}")
    
    # 3. Исправим Employee, у которых нет user или user=None
    for employee in Employee.objects.filter(user__isnull=True):
        # Создаем нового пользователя для этого сотрудника
        user = User.objects.create_user(
            username=f"employee_fix_{employee.id}",
            email=f"employee_fix_{employee.id}@example.com",
            password="temp_password_123"
        )
        employee.user = user
        employee.save()
        print(f"Создан пользователь для сотрудника {employee.id}")

class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_client_created_at_remove_client_email_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_client_employee_users),
    ]
