# Generated by Django 5.2.6 on 2025-11-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_fix_client_employee_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_published',
        ),
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.ImageField(null=True, upload_to='clients', verbose_name='Изображение'),
        ),
    ]
