# Generated by Django 5.2.6 on 2025-11-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_remove_review_is_published_client_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='clients', verbose_name='Фото сотрудника'),
        ),
        migrations.AddField(
            model_name='review',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='clients', verbose_name='Изображение'),
        ),
    ]
