# Generated by Django 5.2.6 on 2025-11-02 17:01

from django.db import migrations
from django.contrib.auth.models import User

from general.models import UserProfile

def create_userprofiles_for_old_users(apps, schema_editor):
    users = User.objects.all()
    for user in users:
        try:
            user.userprofile
        except UserProfile.DoesNotExist:
            UserProfile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_userprofile_birthday_alter_userprofile_fio'),
    ]

    operations = [
    migrations.RunPython(create_userprofiles_for_old_users)
]
