# Generated by Django 5.2.6 on 2025-11-02 19:12

from django.db import migrations
def create_missing_userprofiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('general', 'UserProfile')
    
    # Создаем UserProfile для всех пользователей, у которых его нет
    users_without_profile = User.objects.filter(userprofile__isnull=True)
    
    for user in users_without_profile:
        UserProfile.objects.create(user=user)
        print(f"Создан UserProfile для пользователя {user.username}")
    
    print(f"Создано {users_without_profile.count()} UserProfile")

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20251103_0101'),
    ]

    operations = [
        migrations.RunPython(create_missing_userprofiles),
    ]